name: 'Get Pulumi stack output'
description: 'Retrieve a stack output from an S3 backend'
author: 'RS21'
inputs:
  stack:
    required: true
    description: 'stack whose outputs you want to get'
  output:
    required: true
    description: 'output you want to get'
  cloud-url:
    required: true
    description: 'S3 URI where the stack state is stored'
runs:
  using: 'node16'
  main: 'dist/index.js'
