name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  AWS_REGION: us-west-2

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{secrets.AWS_ARN }} | sed 's/./& /g'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          role-session-name: github-actions
          aws-region: ${{ env.AWS_REGION }}
      - uses: ./
        with:
          stack: cluster.dev
          output: name
          cloud-url: ${{ secrets.BACKEND_URL }}
